### ISSUE TITLE
Use official ARM assembly syntax

### ISSUE THREAD

**Issue by felixjones** [felixjones/agbabi#17]
Would be nice to match modern ARM documentation for all the instructions. `ldmgeia` would become `ldmiage`

**Comment by asiekierka** [comment]
This is also valuable for LLVM/Clang compatibility, IIRC, as that assembler is much more restrictive with regards to what syntax is supported.

**Comment by LunarLambda** [comment]
Would you be accepting a PR for this? I'm fairly good at this and could probably knock it out in one go this afternoon. At least for the GNU toolchain. Unsure if there's other things necessary for LLVM/Clang besides `.syntax unified`.

**Comment by felixjones** [comment]
> Would you be accepting a PR for this? I'm fairly good at this and could probably knock it out in one go this afternoon. At least for the GNU toolchain. Unsure if there's other things necessary for LLVM/Clang besides `.syntax unified`.

Yep PR would of course be accepted, I was also thinking it's something that can be done in one go this afternoon, so it's an up for grabs task 👍
