### ISSUE TITLE
Linking with agbabi breaks calling memcpy/memset from crt0

### ISSUE THREAD

**Issue by LunarLambda** [felixjones/agbabi#21]
`memcpy` and `memset` are placed into IWRAM, which causes problems if the startup code (i.e. `crt0`) tries to call them before copying the IWRAM section.

https://github.com/LunarLambda/sdk-seven/blob/v0.27.1/minrt/src/gba/rt0.s#L65

While for me this most likely means implementing a memcpy/memset for minrt specifically, maybe `agbabi` could place `memcpy` and other libc symbols in ROM and use a runtime check to see if the IWRAM symbols are available, falling back to a slower path?

(it is theoretically be possible to call the un-copied function, but this requires calculating its LMA, which is tricky)

**Comment by felixjones** [comment]
I considered this early on, but really in start-up code there's not only DMA copy (which is faster) but the BIOS CPU copy, so I concluded that it is misguided to use a fast memcpy at start-up

If you really need fast copying at start then you'd be using DMA, not a custom memcpy routine

**Comment by LunarLambda** [comment]
The thing is that I want to avoid needlessly padding/aligning sections. DMA can't deal with byte alignment. The reason is that alignment causes a lot of extraneous sections to be ommitted even if the section is otherwise empty.

**Comment by felixjones** [comment]
You can DMA up to sub-alignment, and then ldm/stm the remaining words
And a linkerscript can set up all constants for this, saving any runtime calculations

**Comment by LunarLambda** [comment]
It seems like maybe I have a working workaround.

update: nope.

**Comment by felixjones** [comment]
I thought about this a whole bunch more and I think I'm at the same conclusion

Checking if the subroutine is loaded in IWRAM is a cost to pay at run-time, for something that's only true at start-time, and on top of that any routine from ROM is likely slower than `CpuFastSet` + a tail copy

In terms of performance, it's DMA, custom routine in IWRAM, and then BIOS routine, and it seems silly to go for something that's worse than BIOS routine for the convenience of `memcpy` called from _assembler code_ with a cost to the copies that actually matter: runtime with IRQ enabled

IMO the best implementation of a runtime is a DMA with a tail copy all defined by linker-script constants. I believe even Tonc's start code copies its IWRAM for `memcpy32` before copying everything else?
