### ISSUE TITLE
0 sized memcopy with alignments 1 and 3 off words causes memory corruption

### ISSUE THREAD

**Issue by gwilymk** [felixjones/agbabi#7]
This is such an edge case :stuck_out_tongue: 

We were still getting crashes with a game written using `agbrs` after the fix for #6 was incorporated. I continued writing tests for memcpy (and memset) to try and trigger this, and found an issue if the source and target are aligned 1 and 3 of words, and the size of the copy is 0 bytes (no idea why rust is deciding to do that with a zero sized copy, I assume because LLVM is much more willing to call out to `__aeabi` methods then GCC is so why this hasn't been spotted already).

The included test case crashes under mgba with

```
[WARN] GBA: Illegal opcode: e710b710
[FATAL] GBA Memory: Jumped to invalid address: BFFFFF02
```

I fixed this in `agb` by moving the check introduced in https://github.com/felixjones/agbabi/commit/831607982e28997dadba619ffe705aa1eeb6da2a to the beginning of the `__aeabi_memcpy` method: https://github.com/agbrs/agb/pull/244/files#diff-14ae7e851f02e42fa19c564aa61ca104aa17ac642fe069156a985156dad836fb

```c
#include <agbabi.h>

extern void __aeabi_memcpy(void *dest, const void *src, size_t n);

int main()
{
    char buffer_char[70] = {0};

    __aeabi_memcpy(buffer_char + 1, buffer_char + 3, 0);

    *(unsigned int *)0x04000000 = 0x0403;

    ((unsigned short *)0x06000000)[120 + 80 * 240] = 0x001F;
    ((unsigned short *)0x06000000)[136 + 80 * 240] = 0x03E0;
    ((unsigned short *)0x06000000)[120 + 96 * 240] = 0x7C00;

    while (1)
        ;
}
```

**Comment by felixjones** [comment]
Thanks for another excellent report!

Latest commit https://github.com/felixjones/agbabi/commit/01e4edbf78c4b6f44fd429bca046d0b820aff97f has a fix for this, and optimises the code a little bit for large copies (small copies are made slower, I expect >4 byte copies to be the common scenario tbh so this trade-off is correct to me)

I'd super appreciate it if you could run this through your tests! memset and memcpy were adjusted (also rmemcpy, but it looks like you don't use memmove so that shouldn't be an issue for your project)

**Comment by gwilymk** [comment]
Thanks for looking into this. I ran memcpy from [your commit](https://github.com/felixjones/agbabi/commit/01e4edbf78c4b6f44fd429bca046d0b820aff97f) and it seems to fail on the same test case? (was able to cause the crash with mgba with the same example included in the issue report :smile:)

**Comment by felixjones** [comment]
Woops I accidentally Ctrl Z'd the fix away

EDIT: Could you please retry with https://github.com/felixjones/agbabi/commit/f4fe1a5ffd6bcec5874423de30b48524bba9e46f?

**Comment by gwilymk** [comment]
apparently there's an underrun with alignment on both source and target `+1` and `n = 2`. Overwrites the byte before it should in the target :).

**Comment by felixjones** [comment]
Alright I've given up on the attempts to optimise it. Latest commit does byte-by-byte copies/sets for <=2 bytes and handles the size=0 issue for half-aligned byte heads
https://github.com/felixjones/agbabi/commit/8f070bf1c3304d5ae57a750d41feea0e189b0f2d

And now I want to re-write the whole thing.

**Comment by gwilymk** [comment]
sorry :(. Let me know if you want some help setting up the agb tests to run locally :). Would hopefully help make the rewrite a bit easier :D.

But with https://github.com/felixjones/agbabi/commit/8f070bf1c3304d5ae57a750d41feea0e189b0f2d, everything is working correctly :grin:

**Comment by felixjones** [comment]
> sorry :(. Let me know if you want some help setting up the agb tests to run locally :). Would hopefully help make the rewrite a bit easier :D.
> 
> But with [8f070bf](https://github.com/felixjones/agbabi/commit/8f070bf1c3304d5ae57a750d41feea0e189b0f2d), everything is working correctly 😁

mGBA has a CTest style API and I have that set up already somewhere, just never got it to a point where the tests were sane enough to include

If everything is working, I'll close
