### ISSUE TITLE
"aeabi functions" link in the readme appears to not work

### ISSUE THREAD

**Issue by Lokathor** [felixjones/agbabi#8]
When i tried to click the link i got a "this page is missing" result from the arm dev portal.

**Comment by felixjones** [comment]
I have no idea where the new page for that is. May need to use a way-back-machine version...

**Comment by Lokathor** [comment]
if it makes you feel better, their own dev portal still has ways to take you to that page which is now missing.

**Comment by felixjones** [comment]
Managed to track down where the document moved to: https://github.com/ARM-software/abi-aa/blob/main/rtabi32/rtabi32.rst
Fixed in https://github.com/felixjones/agbabi/commit/1024a717ffbbfb40c5da1cf16933c1fd0907c036
